package dev.sasikanth.rss.reader.resources.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.FR, default = false)
val FrTwineStrings =
  TwineStrings(
    appName = "Twine",
    postSourceUnknown = "Inconnu",
    buttonAll = "TOUS",
    buttonAddFeed = "Ajouter le flux",
    buttonGoBack = "Annuler",
    buttonCancel = "Annuler",
    buttonAdd = "Ajouter",
    buttonChange = "Terminé",
    buttonConfirm = "Valider",
    feedEntryLinkHint = "Lien du flux",
    feedEntryTitleHint = "Nom (optionnel)",
    share = "Partager",
    scrollToTop = "Haut de page",
    noFeeds = "Aucun flux trouvé !",
    swipeUpGetStarted = "Swipez vers le haut pour commencer",
    feedNameHint = "Nom du flux",
    editFeedName = "Modifier",
    errorUnsupportedFeed = "Le lien ne contient aucun flux RSS/Atom.",
    errorMalformedXml = "Le lien fourni ne contient pas de flux RSS/Atom valide",
    errorRequestTimeout =
      "Délai d’attente dépassé, vérifiez votre connexion réseau et réessayez plus tard",
    errorFeedNotFound = { "($it) : Aucun contenu trouvé à l’adresse indiquée." },
    errorServer = {
      "($it) : Erreur du serveur. Veuillez réessayer plus tard ou contacter l’administrateur du site web."
    },
    errorTooManyRedirects =
      "L’URL donnée comporte trop de redirections. Veuillez utiliser une autre URL.",
    errorUnAuthorized = { "($it) : Vous n’êtes pas autorisé à accéder au contenu de ce lien." },
    errorUnknownHttpStatus = { "Échec de chargement du contenu avec le code HTTP : ($it)" },
    postsSearchHint = "Rechercher des articles",
    searchSortNewest = "Récents",
    searchSortNewestFirst = "Plus récents",
    searchSortOldest = "Anciens",
    searchSortOldestFirst = "Plus anciens",
    searchResultsCount = { count ->
      when (count) {
        0,
        1 -> "$count résultat"
        else -> "$count résultats"
      }
    },
    bookmark = "Favori",
    unBookmark = "Retirer des favoris",
    bookmarks = "Favoris",
    bookmarksPlaceholder = "Les articles ajoutés en favori apparaîtront ici 🔖",
    settings = "Paramètres",
    moreMenuOptions = "Plus d’options",
    settingsHeaderBehaviour = "Comportement",
    settingsHeaderOpml = "OPML",
    settingsHeaderFeedback = "Commentaires & rapports de bugs",
    settingsHeaderTheme = "Thème",
    settingsBrowserTypeTitle = "Utiliser le navigateur intégré",
    settingsBrowserTypeSubtitle =
      "Si désactivé, les liens s’ouvrent dans votre navigateur par défaut.",
    settingsEnableBlurTitle = "Activer le flou sur la page d’accueil",
    settingsEnableBlurSubtitle =
      "Si désactivé, affiche des dégradés au lieu d’images floues. Peut améliorer les performances.",
    settingsShowUnreadCountTitle = "Afficher le nombre d’articles non lus",
    settingsShowUnreadCountSubtitle = "Affiche une pastille dans le sélecteur de flux",
    settingsReportIssue = "Signaler un problème",
    settingsVersion = { versionName, versionCode -> "$versionName ($versionCode)" },
    settingsAboutTitle = "À propos de Twine",
    settingsAboutSubtitle = "Faites connaissance avec les auteurs",
    settingsOpmlImport = "Importer",
    settingsOpmlExport = "Exporter",
    settingsOpmlImporting = { progress -> "Importation.. $progress%" },
    settingsOpmlExporting = { progress -> "Exportation.. $progress%" },
    settingsOpmlCancel = "Annuler",
    settingsPostsDeletionPeriodTitle = "Supprimer les articles lus datant de plus de",
    settingsPostsDeletionPeriodOneWeek = "1 semaine",
    settingsPostsDeletionPeriodOneMonth = "1 mois",
    settingsPostsDeletionPeriodThreeMonths = "3 mois",
    settingsPostsDeletionPeriodSixMonths = "6 mois",
    settingsPostsDeletionPeriodOneYear = "1 an",
    settingsPostsDeletionPeriodNever = "Jamais",
    settingsShowReaderViewTitle = "Activer la vue lecteur",
    settingsShowReaderViewSubtitle =
      "Les articles seront affichés dans une vue simplifiée et facile à lire",
    settingsThemeAuto = "Auto",
    settingsThemeLight = "Clair",
    settingsThemeDark = "Sombre",
    feeds = "Flux",
    editFeeds = "Modifier les flux",
    comments = "Commentaires",
    about = "À propos",
    aboutRoleDeveloper = "Développeur",
    aboutRoleDesigner = "Designer",
    aboutSocialTwitter = "Twitter",
    aboutSocialThreads = "Threads",
    aboutSocialGitHub = "GitHub",
    aboutSocialWebsite = "Site web",
    feedsSearchHint = "Filtrer",
    allFeeds = "Flux",
    pinnedFeeds = "Épinglés",
    markAllAsRead = "Tout marquer comme lu",
    openWebsite = "Ouvrir le site web",
    noNewPosts = "Pas de nouveau contenu",
    noNewPostsSubtitle = "Revenez plus tard ou tirez vers le bas pour actualiser",
    postsAll = "Tous les articles",
    postsUnread = "Non lus",
    postsToday = "Aujourd’hui",
    postsLast24Hours = "Dernières 24 heures",
    openSource = "Soutenir l’Open Source",
    openSourceDesc =
      "Twine est un projet open source et disponible gratuitement. Cliquez ici pour en savoir plus sur la façon de soutenir ce projet, ou pour consulter son code source et d’autres projets populaires.",
    markAsRead = "Marquer comme lu",
    markAsUnRead = "Marquer comme non lu",
    removeFeed = "Supprimer le flux",
    delete = "Supprimer",
    removeFeedDesc = { "Voulez-vous vraiment supprimer « ${it} » ?" },
    alwaysFetchSourceArticle = "Toujours charger l’article complet en mode lecteur",
    getFeedInfo = "Obtenir des infos",
    newTag = "Nouveau tag",
    tags = "Tags",
    addTagTitle = "Ajouter un tag",
    tagNameHint = "Nom",
    tagSaveButton = "Enregistrer",
    deleteTagTitle = "Supprimer le tag ?",
    deleteTagDesc =
      "Le tag sera supprimé de tous les flux qui y sont associés. Vos flux ne seront pas supprimés.",
    feedOptionShare = "Partager",
    feedOptionWebsite = "Site web",
    feedOptionRemove = "Supprimer",
    feedTitleHint = "Nom",
    noUnreadPostsInFeed = "Aucun article non lu",
    numberOfUnreadPostsInFeed = { numberOfUnreadPosts ->
      when (numberOfUnreadPosts) {
        0L,
        1L -> "$numberOfUnreadPosts article non lu"
        else -> "$numberOfUnreadPosts articles non lus"
      }
    },
    feedsSortLatest = "Dernier ajouté",
    feedsSortOldest = "Premier ajouté",
    feedsSortAlphabetical = "A-Z",
    feedsBottomBarNewGroup = "Nouveau groupe",
    feedsBottomBarNewFeed = "Nouveau flux",
    actionPin = "Épingler",
    actionUnpin = "Désépingler",
    actionDelete = "Supprimer",
    actionAddTo = "Ajouter à",
    actionMoveTo = "Déplacer vers",
    actionUngroup = "Retirer",
    createGroup = "Créer un groupe",
    createFeed = "Ajouter un flux",
    groupNameHint = "Nom",
    feedGroupNoFeeds = "Aucun flux",
    feedGroupFeeds = { numberOfFeeds -> "$numberOfFeeds flux" },
    actionGroupsTooltip = "Un groupe ne peut pas être ajouté dans un autre groupe.",
    groupAddNew = "Nouveau",
    appBarAllFeeds = "Tous les flux",
    edit = "Modifier",
    buttonAddToGroup = "Ajouter au groupe…",
    removeSources = "Supprimer les sources",
    removeSourcesDesc = "Voulez-vous supprimer les sources sélectionnées ?",
    noPinnedSources = "Aucun flux ou groupe épinglé",
    databaseMaintainenceTitle = "Veuillez patienter…",
    databaseMaintainenceSubtitle =
      "Maintenance de la base de données en cours, ne fermez pas l’application",
    cdLoadFullArticle = "Charger l’article complet",
    enableAutoSyncTitle = "Activer la synchronisation automatique",
    enableAutoSyncDesc = "Si activé, les flux seront mis à jour en arrière-plan",
    showFeedFavIconTitle = "Afficher le favicon du flux",
    showFeedFavIconDesc =
      "Si désactivé, l’icône du flux sera affichée à la place du favicon du site web",
    blockedWords = "Mots bloqués",
    blockedWordsHint = "Saisir un mot",
    blockedWordsDesc =
      "Les articles peuvent être masqués de l’accueil en fonction de leur texte. Nous vous recommandons d’éviter les mots communs, car cela pourrait empêcher l’affichage de tout article ou nuire aux performances. \n\nLes articles masqués resteront visibles dans les résultats de recherche et les favoris.",
    blockedWordsEmpty = "Vous n’avez pas encore bloqué de mots",
    markArticleAsRead = "Marquer l’article comme lu",
    markArticleAsReadOnOpen = "À l’ouverture",
    markArticleAsReadOnScroll = "Au scroll",
    noReaderContent =
      "Aucun contenu à afficher dans le lecteur. Essayez de charger l’article ou visitez le site web.",
    pullToClose = "Tirer vers le bas pour fermer",
    readerSettings = "Paramètres du lecteur",
    comingSoon = "Bientôt disponible",
    homeViewMode = "Modes d’affichage",
    homeViewModeDefault = "Par défaut",
    homeViewModeSimple = "Simple",
    homeViewModeCompact = "Compact",
  )
