package dev.sasikanth.rss.reader.resources.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.TR, default = false)
val TrTwineStrings =
  TwineStrings(
    appName = "Twine",
    postSourceUnknown = "Bilinmiyor",
    buttonAll = "TÜMÜ",
    buttonAddFeed = "Akış ekle",
    buttonGoBack = "Geri dön",
    buttonCancel = "İptal",
    buttonAdd = "Ekle",
    buttonChange = "Tamam",
    buttonConfirm = "Onayla",
    feedEntryLinkHint = "Akış bağlantısı",
    feedEntryTitleHint = "Başlık (İsteğe bağlı)",
    share = "Paylaş",
    scrollToTop = "Yukarı kaydır",
    noFeeds = "Hiç akış yok!",
    swipeUpGetStarted = "Başlamak için yukarı kaydır",
    feedNameHint = "Akış adı",
    editFeedName = "Düzenle",
    errorUnsupportedFeed = "Bağlantı herhangi bir RSS/Atom akışı içermiyor.",
    errorMalformedXml = "Sağlanan bağlantı geçerli bir RSS/Atom akışı içermiyor.",
    errorRequestTimeout = "Zaman aşımı, ağ bağlantınızı kontrol edin ve daha sonra tekrar deneyin.",
    errorFeedNotFound = { "($it): Verilen bağlantıda içerik bulunamadı." },
    errorServer = {
      "($it): Sunucu hatası. Lütfen daha sonra tekrar deneyin veya web sitesi yöneticisiyle iletişime geçin."
    },
    errorTooManyRedirects = "Verilen URL'de çok fazla yönlendirme var. Lütfen farklı bir URL kullanın.",
    errorUnAuthorized = { "($it): Bu bağlantıdaki içeriğe erişim yetkiniz yok." },
    errorUnknownHttpStatus = { "İçerik yüklenemedi, HTTP kodu: ($it)" },
    postsSearchHint = "Gönderilerde ara",
    searchSortNewest = "En yeni",
    searchSortNewestFirst = "Önce en yeni",
    searchSortOldest = "En eski",
    searchSortOldestFirst = "Önce en eski",
    searchResultsCount = { count ->
      when (count) {
        1 -> "$count sonuç"
        else -> "$count sonuç"
      }
    },
    bookmark = "Yer işareti ekle",
    unBookmark = "Yer işaretini kaldır",
    bookmarks = "Yer işaretleri",
    bookmarksPlaceholder = "Yer işaretine eklenen gönderiler burada görünecek 🔖",
    settings = "Ayarlar",
    moreMenuOptions = "Daha fazla menü seçeneği",
    settingsHeaderBehaviour = "Davranış",
    settingsHeaderOpml = "OPML",
    settingsHeaderFeedback = "Geri bildirim ve hata raporları",
    settingsHeaderTheme = "Tema",
    settingsBrowserTypeTitle = "Uygulama içi tarayıcıyı kullan",
    settingsBrowserTypeSubtitle = "Kapalı olduğunda, bağlantılar varsayılan tarayıcınızda açılır.",
    settingsEnableBlurTitle = "Ana sayfada bulanıklık efektini etkinleştir",
    settingsEnableBlurSubtitle =
      "Devre dışı bırakıldığında, bulanık görüntüler yerine gradyanlar gösterilir. Bu, performansı artırabilir.",
    settingsShowUnreadCountTitle = "Okunmamış gönderi sayısını göster",
    settingsShowUnreadCountSubtitle = "Akış seçimlerinin üzerinde bir balon gösterilir",
    settingsReportIssue = "Sorun bildir",
    settingsVersion = { versionName, versionCode -> "$versionName ($versionCode)" },
    settingsAboutTitle = "Twine Hakkında",
    settingsAboutSubtitle = "Yazarları tanıyın",
    settingsOpmlImport = "İçe aktar",
    settingsOpmlExport = "Dışa aktar",
    settingsOpmlImporting = { progress -> "İçe aktarılıyor.. $progress%" },
    settingsOpmlExporting = { progress -> "Dışa aktarılıyor.. $progress%" },
    settingsOpmlCancel = "İptal",
    settingsPostsDeletionPeriodTitle = "Şu tarihten eski okunmuş gönderileri sil",
    settingsPostsDeletionPeriodOneWeek = "1 hafta",
    settingsPostsDeletionPeriodOneMonth = "1 ay",
    settingsPostsDeletionPeriodThreeMonths = "3 ay",
    settingsPostsDeletionPeriodSixMonths = "6 ay",
    settingsPostsDeletionPeriodOneYear = "1 yıl",
    settingsShowReaderViewTitle = "Okuyucu görünümünü etkinleştir",
    settingsShowReaderViewSubtitle = "Makaleler, sade ve okunması kolay bir görünümde gösterilir",
    settingsThemeAuto = "Otomatik",
    settingsThemeLight = "Açık",
    settingsThemeDark = "Koyu",
    feeds = "Akışlar",
    editFeeds = "Akışları düzenle",
    comments = "Yorumlar",
    about = "Hakkında",
    aboutRoleDeveloper = "Geliştirici",
    aboutRoleDesigner = "Tasarımcı",
    aboutSocialTwitter = "Twitter",
    aboutSocialThreads = "Threads",
    aboutSocialGitHub = "GitHub",
    aboutSocialWebsite = "Web sitesi",
    feedsSearchHint = "Filtrele",
    allFeeds = "Tüm akışlar",
    pinnedFeeds = "Sabitlenmiş akışlar",
    markAllAsRead = "Tümünü okundu olarak işaretle",
    openWebsite = "Web sitesini aç",
    noNewPosts = "Yeni içerik yok",
    noNewPostsSubtitle = "Daha sonra tekrar kontrol edin veya şimdi yeni içerik için aşağı çekin",
    postsAll = "Tüm makaleler",
    postsUnread = "Okunmamış",
    postsToday = "Bugün",
    postsLast24Hours = "Son 24 saat",
    openSource = "Açık Kaynağı Destekle",
    openSourceDesc =
      "Twine bir açık kaynak projesidir ve ücretsiz olarak kullanılabilir. Bu projeyi desteklemek veya Twine'ın ya da diğer popüler projelerimin kaynak kodunu görmek için buraya tıklayın.",
    markAsRead = "Okundu olarak işaretle",
    markAsUnRead = "Okunmamış olarak işaretle",
    removeFeed = "Akışı kaldır",
    delete = "Sil",
    removeFeedDesc = { "\"${it}\" akışını kaldırmak istiyor musunuz?" },
    alwaysFetchSourceArticle = "Okuyucu görünümünde her zaman tam makaleleri al",
    getFeedInfo = "Bilgi al",
    newTag = "Yeni etiket",
    tags = "Etiketler",
    addTagTitle = "Etiket ekle",
    tagNameHint = "Ad",
    tagSaveButton = "Kaydet",
    deleteTagTitle = "Etiketi sil?",
    deleteTagDesc =
      "Etiket silinecek ve atanmış tüm akışlardan kaldırılacak. Akışlarınız silinmeyecek.",
    feedOptionShare = "Paylaş",
    feedOptionWebsite = "Web sitesi",
    feedOptionRemove = "Kaldır",
    feedTitleHint = "Başlık",
    noUnreadPostsInFeed = "Okunmamış makale yok",
    numberOfUnreadPostsInFeed = { numberOfUnreadPosts ->
      when (numberOfUnreadPosts) {
        1L -> "$numberOfUnreadPosts okunmamış makale"
        else -> "$numberOfUnreadPosts okunmamış makale"
      }
    },
    feedsSortLatest = "Son eklenen",
    feedsSortOldest = "İlk eklenen",
    feedsSortAlphabetical = "A-Z",
    feedsBottomBarNewGroup = "Yeni grup",
    feedsBottomBarNewFeed = "Yeni akış",
    actionPin = "Sabitle",
    actionUnpin = "Sabitlemeyi kaldır",
    actionDelete = "Sil",
    actionAddTo = "Ekle",
    actionMoveTo = "Taşı",
    actionUngroup = "Grubu kaldır",
    createGroup = "Grup oluştur",
    createFeed = "Akış ekle",
    groupNameHint = "Ad",
    feedGroupNoFeeds = "Akış yok",
    feedGroupFeeds = { numberOfFeeds ->
      when (numberOfFeeds) {
        1 -> "$numberOfFeeds akış"
        else -> "$numberOfFeeds akış"
      }
    },
    actionGroupsTooltip = "Gruplar başka grupların içinde olamaz.",
    groupAddNew = "Yeni ekle",
    appBarAllFeeds = "Tüm akışlar",
    edit = "Düzenle",
    buttonAddToGroup = "Gruba ekle...",
    removeSources = "Kaynakları sil",
    removeSourcesDesc = "Seçilen kaynakları silmek istiyor musunuz?",
    noPinnedSources = "Sabitlenmiş akış/grup yok",
    databaseMaintainenceTitle = "Lütfen bekleyin...",
    databaseMaintainenceSubtitle = "Veritabanı bakımı yapılıyor, uygulamayı kapatmayın",
    cdLoadFullArticle = "Tam makaleyi yükle",
    enableAutoSyncTitle = "Otomatik senkronizasyonu etkinleştir",
    enableAutoSyncDesc = "Açıldığında, akışlar arka planda güncellenir",
    showFeedFavIconTitle = "Akış favicon'unu göster",
    showFeedFavIconDesc =
      "Kapalı olduğunda, web sitesinin favicon'u yerine akış simgesi gösterilir",
    blockedWords = "Engellenen kelimeler",
    blockedWordsHint = "Bir kelime girin",
    blockedWordsDesc =
      "Gönderiler, metinlerine göre ana ekrandan gizlenebilir. Çok yaygın kelimeler kullanmaktan kaçınmanızı öneririz, çünkü bu, hiçbir gönderinin gösterilmemesine veya uygulamanın performansının olumsuz etkilenmesine neden olabilir. \n\nGizlenen gönderiler arama ve yer işaretlerinde hâlâ görünecektir.",
    blockedWordsEmpty = "Henüz hiçbir kelimeyi engellemediniz",
    markArticleAsRead = "Makaleyi okundu olarak işaretle",
    markArticleAsReadOnOpen = "Açıldığında",
    markArticleAsReadOnScroll = "Kaydırıldığında",
    noReaderContent =
      "Okuyucuda görüntülenecek içerik yok, lütfen makaleyi almayı deneyin veya web sitesini ziyaret edin.",
    pullToClose = "Kapatmak için aşağı çekin",
    readerSettings = "Okuyucu ekranı ayarları",
    comingSoon = "Yakında",
    homeViewMode = "Görünüm modları",
    homeViewModeDefault = "Varsayılan",
    homeViewModeSimple = "Basit",
    homeViewModeCompact = "Kompakt",
  )
