package dev.sasikanth.rss.reader.resources.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.TR, default = false)
val TrTwineStrings =
  TwineStrings(
    appName = "Twine",
    postSourceUnknown = "Bilinmiyor",
    buttonAll = "TÜMÜ",
    buttonAddFeed = "İçerik ekle",
    buttonGoBack = "Geri dön",
    buttonCancel = "İptal",
    buttonAdd = "Ekle",
    buttonChange = "Bitti",
    buttonConfirm = "Onayla",
    feedEntryLinkHint = "Yayın bağlantısı",
    feedEntryTitleHint = "Başlık (İsteğe Bağlı)",
    share = "Paylaş",
    scrollToTop = "Yukarı kaydır",
    noFeeds = "İçerik yok!",
    swipeUpGetStarted = "Başlamak için yukarı kaydırın",
    feedNameHint = "Yayın adı",
    editFeedName = "Düzenle",
    errorUnsupportedFeed = "Bağlantı herhangi bir RSS/Atom yayını içermiyor.",
    errorMalformedXml = "Bağlantı geçerli RSS/Atom yayını içermiyor",
    errorRequestTimeout = "Zaman aşımı, ağ bağlantınızı kontrol edin ve daha sonra tekrar deneyin",
    errorFeedNotFound = { "($it): Verilen bağlantıda yayın bulunamadı." },
    errorServer = {
      "($it): Sunucu hatası. Lütfen daha sonra tekrar deneyin veya web sitesi yöneticisiyle iletişime geçin."
    },
    errorTooManyRedirects =
      "Verilen URL'de çok fazla yönlendirme var. Lütfen farklı bir URL kullanın.",
    errorUnAuthorized = { "($it): Bu bağlantıdaki içeriğe erişim yetkiniz bulunmamaktadır." },
    errorUnknownHttpStatus = { "HTTP koduna sahip yayın yüklenemedi: ($it)" },
    postsSearchHint = "Gönderileri ara",
    searchSortNewest = "En Yeni",
    searchSortNewestFirst = "Önce en yeni",
    searchSortOldest = "En eski",
    searchSortOldestFirst = "Önce en eski",
    searchResultsCount = { count ->
      when (count) {
        1 -> "$count sonuç"
        else -> "$count sonuçlar"
      }
    },
    bookmark = "Yer İşareti",
    unBookmark = "Un-bookmark",
    bookmarks = "Yer İşaretleri",
    bookmarksPlaceholder = "Yer imlerine eklenen gönderiler burada görünecektir 🔖",
    settings = "Ayarlar",
    moreMenuOptions = "Daha fazla menü seçeneği",
    settingsHeaderBehaviour = "Davranış",
    settingsHeaderOpml = "OPML",
    settingsHeaderFeedback = "Geri bildirim & Hata raporları",
    settingsHeaderTheme = "Theme",
    settingsBrowserTypeTitle = "Uygulama içi tarayıcıyı kullan",
    settingsBrowserTypeSubtitle =
      "Kapatıldığında, bağlantılar varsayılan tarayıcınızda açılacaktır.",
    settingsEnableBlurTitle = "Ana sayfada bulanıklaştırmayı etkinleştir",
    settingsEnableBlurSubtitle =
      "Devre dışı bırakıldığında, bulanık görüntüler yerine gradyanları görüntüler. Performansı artırabilir.",
    settingsShowUnreadCountTitle = "Okunmamış gönderi sayısını göster",
    settingsShowUnreadCountSubtitle = "İçerik seçimlerinin üzerinde bir baloncuk görüntüler.",
    settingsReportIssue = "Sorun bildir",
    settingsVersion = { versionName, versionCode -> "$versionName ($versionCode)" },
    settingsAboutTitle = "Twine hakkında",
    settingsAboutSubtitle = "Yazarları tanıyın",
    settingsOpmlImport = "İçe aktar",
    settingsOpmlExport = "Dışa aktar",
    settingsOpmlImporting = { progress -> "İçe aktarılıyor.. $progress%" },
    settingsOpmlExporting = { progress -> "Dışa aktarılıyor.. $progress%" },
    settingsOpmlCancel = "İptal",
    settingsPostsDeletionPeriodTitle = "Okunmuş gönderileri sil",
    settingsPostsDeletionPeriodOneWeek = "1 hafta",
    settingsPostsDeletionPeriodOneMonth = "1 ay",
    settingsPostsDeletionPeriodThreeMonths = "3 ay",
    settingsPostsDeletionPeriodSixMonths = "6 ay",
    settingsPostsDeletionPeriodOneYear = "1 yıl",
    settingsShowReaderViewTitle = "Okuyucu görünümünü etkinleştir",
    settingsShowReaderViewSubtitle =
      "Gönderiler basitleştirilmiş, okunması kolay bir görünümde gösterilecek.",
    settingsThemeAuto = "Auto",
    settingsThemeLight = "Light",
    settingsThemeDark = "Dark",
    feeds = "İçerikler",
    editFeeds = "İçerikleri düzenle",
    comments = "Yorumlar",
    about = "Hakkında",
    aboutRoleDeveloper = "Geliştirici",
    aboutRoleDesigner = "Tasarımcı",
    aboutSocialTwitter = "Twitter",
    aboutSocialThreads = "Threads",
    aboutSocialGitHub = "GitHub",
    aboutSocialWebsite = "Web sitesi",
    feedsSearchHint = "Filtre",
    allFeeds = "Yayınlar",
    pinnedFeeds = "Sabitlenmiş",
    markAllAsRead = "Tümünü okundu olarak işaretle",
    openWebsite = "Web sitesini aç",
    noNewPosts = "Yeni gönderi yok",
    noNewPostsSubtitle =
      "Daha sonra tekrar kontrol edin veya yeni içeriği şimdi kontrol etmek için aşağı çekin",
    postsAll = "Tüm gönderiler",
    postsUnread = "Okunmamış",
    postsToday = "Bugün",
    postsLast24Hours = "Son 24 saat",
    openSource = "Açık kaynağı destekle",
    openSourceDesc =
      "Twine açık kaynaklı bir projedir ve ücretsiz olarak kullanılabilir. Bu projeyi nasıl destekleyeceğiniz hakkında daha fazla bilgi edinmek için buraya tıklayın veya Twine'ın veya diğer popüler projelerimden bazılarının kaynak kodunu görüntüleyin.",
    markAsRead = "Okundu olarak işaretle",
    markAsUnRead = "Okunmamış olarak işaretle",
    removeFeed = "İçeriği kaldır",
    delete = "Sil",
    removeFeedDesc = { "\"${it}\"'i kaldırmak istiyor musunuz?" },
    alwaysFetchSourceArticle = "Okuyucu görünümünde her zaman tam gönderileri getir",
    getFeedInfo = "Bilgi al",
    newTag = "Yeni etiket",
    tags = "Etiketler",
    addTagTitle = "Etiket ekle",
    tagNameHint = "Ad",
    tagSaveButton = "Kaydet",
    deleteTagTitle = "Etiket silinsin mi?",
    deleteTagDesc =
      "Etiket silinecek ve atanan tüm yayınlarınızdan kaldırılacaktır. İçerikleriniz silinmeyecek",
    feedOptionShare = "Paylaş",
    feedOptionWebsite = "Web sitesi",
    feedOptionRemove = "Kaldır",
    feedTitleHint = "Başlık",
    noUnreadPostsInFeed = "Okunmamış gönderi yok",
    numberOfUnreadPostsInFeed = { numberOfUnreadPosts ->
      when (numberOfUnreadPosts) {
        1L -> "$numberOfUnreadPosts okunmamış gönderi"
        else -> "$numberOfUnreadPosts okunmamış gönderiler"
      }
    },
    feedsSortLatest = "En son eklenen",
    feedsSortOldest = "İlk eklenen",
    feedsSortAlphabetical = "A-Z",
    feedsBottomBarNewGroup = "Yeni Grup",
    feedsBottomBarNewFeed = "Yeni Yayın",
    actionPin = "Sabitle",
    actionUnpin = "Sabitlemeyi Kaldır",
    actionDelete = "Sil",
    actionAddTo = "Şuraya ekle",
    actionMoveTo = "Şuraya taşı",
    actionUngroup = "Gruplandırılmamış",
    createGroup = "Grup oluştur",
    createFeed = "İçerik ekle",
    groupNameHint = "İsim",
    feedGroupNoFeeds = "Yayın yok",
    feedGroupFeeds = { numberOfFeeds ->
      when (numberOfFeeds) {
        1 -> "$numberOfFeeds yayın"
        else -> "$numberOfFeeds yayınlar"
      }
    },
    actionGroupsTooltip = "Gruplar başka grupların içinde olamaz.",
    groupAddNew = "Yeni ekle",
    appBarAllFeeds = "Tüm yayınlar",
    edit = "Düzenle",
    buttonAddToGroup = "Gruba ekle...",
    removeSources = "Kaynakları sil",
    removeSourcesDesc = "Seçili kaynakları silmek istiyor musunuz?",
    noPinnedSources = "Sabitlenmiş yayın/grup yok",
    databaseMaintainenceTitle = "Lütfen bekleyin...",
    databaseMaintainenceSubtitle = "Veritabanı bakımı gerçekleştiriliyor, uygulamayı kapatmayın",
    cdLoadFullArticle = "Load full article",
    enableAutoSyncTitle = "Enable auto sync",
    enableAutoSyncDesc = "When turned-on, feeds will be updated in the background",
    showFeedFavIconTitle = "Show feed fav icon",
    showFeedFavIconDesc =
      "When turned-off, the feed icon will be displayed instead of the website's favicon",
    blockedWords = "Blocked words",
    blockedWordsHint = "Enter a word",
    blockedWordsDesc =
      "Post can be hidden from the home screen based on their text. We recommend avoiding common words that appear in many posts, since it can result in no posts being shown or negatively impacting app performance. \n\nHidden posts will still be displayed in search & bookmarks.",
    blockedWordsEmpty = "You haven't blocked any words yet",
    markArticleAsRead = "Mark article as read",
    markArticleAsReadOnOpen = "On Open",
    markArticleAsReadOnScroll = "On Scroll",
    noReaderContent =
      "No content to display in the reader, please try fetching article or visiting the website.",
  )
