package dev.sasikanth.rss.reader.resources.strings

import cafe.adriel.lyricist.LyricistStrings

@LyricistStrings(languageTag = Locales.ZH, default = false)
val ZhTwineStrings =
  TwineStrings(
    appName = "Twine",
    postSourceUnknown = "未知",
    buttonAll = "全部",
    buttonAddFeed = "添加订阅",
    buttonGoBack = "返回",
    buttonCancel = "取消",
    buttonAdd = "添加",
    buttonChange = "完成",
    buttonConfirm = "确认",
    feedEntryLinkHint = "订阅链接",
    feedEntryTitleHint = "标题（可选）",
    share = "分享",
    scrollToTop = "返回顶部",
    noFeeds = "暂无订阅！",
    swipeUpGetStarted = "向上划动以开始使用",
    feedNameHint = "订阅名称",
    editFeedName = "编辑",
    errorUnsupportedFeed = "链接不包含任何 RSS/Atom 订阅源。",
    errorMalformedXml = "提供的链接不包含有效的 RSS/Atom 订阅源",
    errorRequestTimeout = "请求超时，请检查你的网络连接并稍后重试",
    errorFeedNotFound = { "($it)：在提供的链接中未找到任何内容。" },
    errorServer = { "($it)：服务器错误。请稍后再试或联系网站管理员。" },
    errorTooManyRedirects = "提供的 URL 包含过多重定向。请使用其他 URL。",
    errorUnAuthorized = { "($it)：你没有权限访问链接上的内容。" },
    errorUnknownHttpStatus = { "加载内容失败，HTTP 状态码：($it)" },
    postsSearchHint = "搜索文章",
    searchSortNewest = "最新",
    searchSortNewestFirst = "最新优先",
    searchSortOldest = "最早",
    searchSortOldestFirst = "最早优先",
    searchResultsCount = { count ->
      when (count) {
        1 -> "$count 个结果"
        else -> "$count 个结果"
      }
    },
    bookmark = "收藏",
    unBookmark = "取消收藏",
    bookmarks = "收藏夹",
    bookmarksPlaceholder = "收藏的文章将显示在这里 🔖",
    settings = "设置",
    moreMenuOptions = "更多菜单选项",
    settingsHeaderBehaviour = "行为",
    settingsHeaderOpml = "OPML",
    settingsHeaderFeedback = "反馈与错误报告",
    settingsHeaderTheme = "主题",
    settingsBrowserTypeTitle = "使用应用内浏览器",
    settingsBrowserTypeSubtitle = "如果关闭，链接将在你的默认浏览器中打开。",
    settingsEnableBlurTitle = "在主页启用模糊效果",
    settingsEnableBlurSubtitle = "如果禁用，将使用渐变替换图像模糊效果。或许能提高性能。",
    settingsShowUnreadCountTitle = "显示未读文章的数量",
    settingsShowUnreadCountSubtitle = "在订阅选择上方显示未读气泡",
    settingsReportIssue = "报告问题",
    settingsVersion = { versionName, versionCode -> "$versionName ($versionCode)" },
    settingsAboutTitle = "关于 Twine",
    settingsAboutSubtitle = "了解开发人员",
    settingsOpmlImport = "导入",
    settingsOpmlExport = "导出",
    settingsOpmlImporting = { progress -> "正在导入……$progress%" },
    settingsOpmlExporting = { progress -> "正在导出……$progress%" },
    settingsOpmlCancel = "取消",
    settingsPostsDeletionPeriodTitle = "删除已读文章",
    settingsPostsDeletionPeriodOneWeek = "一周",
    settingsPostsDeletionPeriodOneMonth = "一个月",
    settingsPostsDeletionPeriodThreeMonths = "三个月",
    settingsPostsDeletionPeriodSixMonths = "六个月",
    settingsPostsDeletionPeriodOneYear = "一年",
    settingsShowReaderViewTitle = "启用阅读视图",
    settingsShowReaderViewSubtitle = "文章将以简化、易读的视图显示",
    settingsThemeAuto = "自动",
    settingsThemeLight = "浅色",
    settingsThemeDark = "深色",
    feeds = "订阅",
    editFeeds = "编辑订阅",
    comments = "评论",
    about = "关于",
    aboutRoleDeveloper = "开发者",
    aboutRoleDesigner = "设计师",
    aboutSocialTwitter = "Twitter",
    aboutSocialThreads = "Threads",
    aboutSocialGitHub = "GitHub",
    aboutSocialWebsite = "网站",
    feedsSearchHint = "筛选",
    allFeeds = "所有订阅",
    pinnedFeeds = "已置顶的订阅",
    markAllAsRead = "全部标记为已读",
    openWebsite = "打开网站",
    noNewPosts = "暂无新内容",
    noNewPostsSubtitle = "请稍后回来，或下拉以检查是否有新的内容。",
    postsAll = "所有文章",
    postsUnread = "未读",
    postsToday = "今天",
    postsLast24Hours = "最近 24 小时",
    openSource = "支持开源",
    openSourceDesc = "Twine 是一个开源项目，您可以免费使用。想了解如何支持这个项目，或者想看看 Twine 的源代码以及我其他受欢迎的项目，请点击这里。",
    markAsRead = "标记为已读",
    markAsUnRead = "标记为未读",
    removeFeed = "移除订阅",
    delete = "删除",
    removeFeedDesc = { "你确定要移除 \"${it}\"?" },
    alwaysFetchSourceArticle = "始终在阅读视图中获取完整文章",
    getFeedInfo = "获取信息",
    newTag = "新标签",
    tags = "标签",
    addTagTitle = "添加标签",
    tagNameHint = "名称",
    tagSaveButton = "保存",
    deleteTagTitle = "删除标签？",
    deleteTagDesc = "标签将被删除并从所有已关联的订阅中移除。你的订阅不会被删除。",
    feedOptionShare = "分享",
    feedOptionWebsite = "网站",
    feedOptionRemove = "移除",
    feedTitleHint = "标题",
    noUnreadPostsInFeed = "暂无未读文章",
    numberOfUnreadPostsInFeed = { numberOfUnreadPosts ->
      when (numberOfUnreadPosts) {
        1L -> "$numberOfUnreadPosts 篇未读文章"
        else -> "$numberOfUnreadPosts 篇未读文章"
      }
    },
    feedsSortLatest = "最新添加",
    feedsSortOldest = "最早添加",
    feedsSortAlphabetical = "A-Z",
    feedsBottomBarNewGroup = "新建分组",
    feedsBottomBarNewFeed = "新建订阅",
    actionPin = "置顶",
    actionUnpin = "取消置顶",
    actionDelete = "删除",
    actionAddTo = "添加至",
    actionMoveTo = "移动至",
    actionUngroup = "取消分组",
    createGroup = "创建分组",
    createFeed = "添加订阅",
    groupNameHint = "名称",
    feedGroupNoFeeds = "没有订阅",
    feedGroupFeeds = { numberOfFeeds ->
      when (numberOfFeeds) {
        1 -> "$numberOfFeeds 个订阅"
        else -> "$numberOfFeeds 个订阅"
      }
    },
    actionGroupsTooltip = "分组不能包含在其他分组中。",
    groupAddNew = "新增分组",
    appBarAllFeeds = "所有订阅",
    edit = "编辑",
    buttonAddToGroup = "添加至分组……",
    removeSources = "删除来源",
    removeSourcesDesc = "你确定要删除所选的来源吗？",
    noPinnedSources = "没有置顶的订阅/分组",
    databaseMaintainenceTitle = "请稍候……",
    databaseMaintainenceSubtitle = "正在维护数据库，请勿关闭应用",
    cdLoadFullArticle = "加载完整文章内容",
    enableAutoSyncTitle = "启用自动同步",
    enableAutoSyncDesc = "开启后，订阅将在后台自动更新",
    showFeedFavIconTitle = "显示订阅图标",
    showFeedFavIconDesc =
      "关闭后，将显示订阅图标而不是订阅源的网站图标",
    blockedWords = "已屏蔽的关键词",
    blockedWordsHint = "输入关键词",
    blockedWordsDesc =
      "基于文本内容检测从主屏中隐藏特定文章。我们建议避开大部分文章中会出现的常用词，因为它们可能会导致文章内容不可见或对应用性能造成负面影响。\n\n已隐藏的文章仍会在搜索和收藏夹中可见。",
    blockedWordsEmpty = "你还没有设置任何屏蔽词",
    markArticleAsRead = "标记文章为已读",
    markArticleAsReadOnOpen = "打开后",
    markArticleAsReadOnScroll = "滚动时",
    noReaderContent =
      "阅读器中没有可显示内容，请尝试获取文章或访问网站。",
    pullToClose = "下划关闭",
    readerSettings = "阅读器界面设置",
  )
