"files": [
  {
    "source": "/shared/src/commonMain/composeResources/values/strings.xml",
    "translation": "/shared/src/commonMain/composeResources/values-%two_letters_code%/strings.xml",
    "escape_special_characters": 0
  }
]
