/*
 * Copyright 2026 Sasikanth Miriyampalli
 *
 * Licensed under the GPL, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.sasikanth.rss.reader.data.utils

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse

class SecureRandomTest {

  @Test
  fun generateSecureRandomBytes_shouldReturnCorrectSize() {
    val size = 32
    val bytes = generateSecureRandomBytes(size)
    assertEquals(size, bytes.size)
  }

  @Test
  fun generateSecureRandomBytes_shouldReturnDifferentBytes() {
    val size = 32
    val bytes1 = generateSecureRandomBytes(size)
    val bytes2 = generateSecureRandomBytes(size)

    assertFalse(bytes1.contentEquals(bytes2), "Generated bytes should be different")
  }
}
