[versions]
sdk-compile = "32"
sdk-min = "23"
sdk-target = "32"

compose-compiler = "1.2.0"
compose-ui = "1.2.0-rc03"
compose-material = "1.0.0-alpha14"

agp = "7.2.1"

kotlin = "1.7.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-activity = "androidx.activity:activity-compose:1.5.0"
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.0"
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-material = { module = "androidx.compose.material3:material3", version.ref = "compose-material" }

androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
junit = "junit:junit:4.13.2"

[bundles]
compose = ["compose-ui", "compose-ui-tooling-preview", "compose-material"]
