#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="${HOME}/.config/twine-fork-release.env"
mkdir -p "$(dirname "$ENV_FILE")"
export GH_REPO="${GH_REPO:-camilopaezz/twine}"

banner "Twine fork — GitHub Releases (Android APK + Windows MSI + Linux DEB)"

# ── 1. Enable Actions on the fork ─────────────────────────────────────────
stage "Enable GitHub Actions"
say "Forks ship with workflows disabled until you opt in once."
open_url "https://github.com/camilopaezz/twine/actions"
step "If GitHub shows a banner, click: I understand my workflows, go ahead and enable them."
step "You should then see workflows: CI, Upload FOSS Release to GitHub Release, Desktop Distributables."
pause "Press Enter once Actions are enabled (or already were)."

# ── 2. Workflow write permission (needed to attach release assets) ────────
stage "Actions write permission"
say "Uploading APK/MSI/DEB to a Release needs GITHUB_TOKEN with contents: write."
open_url "https://github.com/camilopaezz/twine/settings/actions"
step "Scroll to Workflow permissions."
step "Select Read and write permissions."
step "Click Save."
pause "Press Enter once that setting is saved."

# ── 3. Create + encrypt Android release keystore ──────────────────────────
stage "Android release keystore"
say "CI decrypts release/reader.gpg → reader.jks. Alias must be reader_alias."
note "Passwords are saved only to $ENV_FILE (outside the repo)."

if [[ -f "$REPO_ROOT/release/reader.gpg" ]] && ! confirm "release/reader.gpg already exists — recreate it?"; then
  say "Keeping existing release/reader.gpg."
  ask_secret KEYSTORE_ENCRYPT_KEY "GPG passphrase used for the existing reader.gpg:"
  ask_secret READER_KEYSTORE_PASSWORD "Keystore (store) password:"
  ask_secret READER_KEY_PASSWORD "Key password (often same as store):"
else
  command -v keytool >/dev/null 2>&1 || { warn "keytool not found (need a JDK on PATH)"; exit 1; }
  command -v gpg >/dev/null 2>&1 || { warn "gpg not found"; exit 1; }

  ask_secret READER_KEYSTORE_PASSWORD "Choose keystore store password:"
  [[ -n "$READER_KEYSTORE_PASSWORD" ]] || { warn "store password cannot be empty"; exit 1; }
  ask_secret READER_KEY_PASSWORD "Choose key password (Enter = same as store):"
  [[ -z "$READER_KEY_PASSWORD" ]] && READER_KEY_PASSWORD="$READER_KEYSTORE_PASSWORD"
  ask_secret KEYSTORE_ENCRYPT_KEY "Choose GPG passphrase to encrypt the keystore for git:"
  [[ -n "$KEYSTORE_ENCRYPT_KEY" ]] || { warn "GPG passphrase cannot be empty"; exit 1; }

  TMPDIR_KS=$(mktemp -d)
  JKS="$TMPDIR_KS/reader.jks"
  cleanup_ks() { rm -rf "$TMPDIR_KS"; }
  trap cleanup_ks EXIT

  step "Generating keystore (alias=reader_alias, RSA 2048, 10000 days)…"
  keytool -genkeypair \
    -keystore "$JKS" \
    -alias reader_alias \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000 \
    -storepass "$READER_KEYSTORE_PASSWORD" \
    -keypass "$READER_KEY_PASSWORD" \
    -dname "CN=Twine FOSS, OU=Personal, O=camilopaezz, C=US"

  mkdir -p "$REPO_ROOT/release"
  rm -f "$REPO_ROOT/release/reader.gpg"
  step "Encrypting to release/reader.gpg…"
  gpg --batch --yes --pinentry-mode loopback \
    --passphrase "$KEYSTORE_ENCRYPT_KEY" \
    --symmetric --cipher-algo AES256 \
    -o "$REPO_ROOT/release/reader.gpg" \
    "$JKS"

  cleanup_ks
  trap - EXIT

  if [[ ! -s "$REPO_ROOT/release/reader.gpg" ]]; then
    warn "release/reader.gpg missing or empty — aborting"
    exit 1
  fi
  say "Created release/reader.gpg ($(wc -c < "$REPO_ROOT/release/reader.gpg") bytes)."
  warn "Never commit a plaintext .jks. Only the encrypted reader.gpg goes in git."
fi

write_env KEYSTORE_ENCRYPT_KEY "$KEYSTORE_ENCRYPT_KEY"
write_env READER_KEYSTORE_PASSWORD "$READER_KEYSTORE_PASSWORD"
write_env READER_KEY_PASSWORD "$READER_KEY_PASSWORD"

# ── 4. GitHub Actions secrets ─────────────────────────────────────────────
stage "GitHub Actions secrets"
say "These three secrets are what android_foss_github_release.yml reads."
note "Repo: $GH_REPO"
if confirm "Set KEYSTORE_ENCRYPT_KEY, READER_KEYSTORE_PASSWORD, READER_KEY_PASSWORD via gh now?"; then
  set_secret KEYSTORE_ENCRYPT_KEY "$KEYSTORE_ENCRYPT_KEY"
  set_secret READER_KEYSTORE_PASSWORD "$READER_KEYSTORE_PASSWORD"
  set_secret READER_KEY_PASSWORD "$READER_KEY_PASSWORD"
else
  open_url "https://github.com/camilopaezz/twine/settings/secrets/actions"
  step "New repository secret → KEYSTORE_ENCRYPT_KEY"
  step "New repository secret → READER_KEYSTORE_PASSWORD"
  step "New repository secret → READER_KEY_PASSWORD"
  pause "Press Enter once all three secrets exist."
fi

# ── 5. Ship checklist ─────────────────────────────────────────────────────
stage "Commit, push, first Release"
say "Repo changes to include: workflows, applicationId, release/reader.gpg, README."
step "From $REPO_ROOT, review with: git status && git diff"
step "Commit and push to main (include release/reader.gpg — it is encrypted)."
step "Then: GitHub → Releases → Draft a new release → tag e.g. v0.1.0 → Publish."
step "Expect assets: androidApp-foss-release.apk, a .msi, and a .deb."
note "Manual desktop rebuild later: Actions → Desktop Distributables → Run workflow."
open_url "https://github.com/camilopaezz/twine/releases/new"
pause "Press Enter when you're done (or after noting the checklist)."

finish
say "Next: commit + push, then publish a Release tag to cut Android/Windows/Linux builds."
