name: Upload FOSS Release to GitHub Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
      ORG_GRADLE_PROJECT_READER_KEYSTORE_PASSWORD: ${{ secrets.READER_KEYSTORE_PASSWORD }}
      ORG_GRADLE_PROJECT_READER_KEY_PASSWORD: ${{ secrets.READER_KEY_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu
          cache: 'gradle'

      - name: Setup versionName from Release Tag
        run: |
          VERSION_NAME=${{ github.event.release.tag_name }}
          echo "ORG_GRADLE_PROJECT_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Setup versionCode
        run: |
          VERSION_CODE=$((2000 + ${{ github.run_number }}))
          echo "ORG_GRADLE_PROJECT_VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Decrypt secrets
        env:
          KEYSTORE_ENCRYPT_KEY: ${{ secrets.KEYSTORE_ENCRYPT_KEY }}
        run: gpg --batch --yes --quiet --pinentry-mode loopback --passphrase "$KEYSTORE_ENCRYPT_KEY" --decrypt --output release/reader.jks release/reader.gpg

      - name: Build FOSS release artifact
        run: ./gradlew --no-daemon androidApp:assembleFossRelease -Ptwine.isFoss=true

      - name: Upload artifact to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} androidApp/build/outputs/apk/foss/release/androidApp-foss-release.apk --clobber

      - name: Clean secrets
        if: always()
        run: |
          rm -f release/reader.jks
